# Generated by Django 4.2 on 2023-04-21 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=600)),
                ("background_image_url", models.CharField()),
                ("hackathon_image_url", models.CharField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("reward_prize", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_hackathon_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registerd_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registered_hackathon_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("summary", models.CharField(max_length=300)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.hackathon",
                    ),
                ),
            ],
        ),
    ]
