# Generated by Django 4.2 on 2023-04-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hackathon",
            old_name="registerd_users",
            new_name="registered_users",
        ),
    ]
