# Generated by Django 4.2 on 2023-04-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0005_submission_created_at_alter_hackathon_reward_prize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
