# Generated by Django 4.2 on 2023-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0006_alter_submission_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="submission_type",
            field=models.CharField(
                choices=[("IMAGE", "IMAGE"), ("FILE", "FILE"), ("LINK", "LINK")],
                default="IMAGE",
            ),
        ),
    ]
