# Generated by Django 4.2 on 2023-04-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0007_hackathon_submission_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="submission_type",
            field=models.CharField(
                choices=[("IMAGE", "IMAGE"), ("FILE", "FILE"), ("LINK", "LINK")]
            ),
        ),
    ]
