# Generated by Django 4.2 on 2023-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0008_alter_hackathon_submission_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="accepted",),
        migrations.AddField(
            model_name="submission",
            name="type",
            field=models.CharField(
                choices=[("IMAGE", "IMAGE"), ("FILE", "FILE"), ("LINK", "LINK")],
                default="LINK",
            ),
            preserve_default=False,
        ),
    ]
